### ISSUE TITLE
Consider using queue interprop as abstraction for queues

### ISSUE THREAD

**Issue by makasim** [mikemadisonweb/yii2-rabbitmq#29]
Hello!

Please look at https://github.com/queue-interop/queue-interop project. Using interfaces from it allows us reuse some implementations like enqueue, which supports a lot of transports. You can outsource some code

**Comment by mikemadisonweb** [comment]
Hello,
Thanks for the suggestion, but I can't say that I completely get the whole idea behind it. There is already a yiisoft/yii2-queue package which provides that type of abstraction between transports. This extension provides deep integration with RabbitMQ only, which can be handy if you are not bothered about other transports and need some unique features that RabbitMq has, rather than basic functionality.

**Comment by mikemadisonweb** [comment]
Issue closed due to inactivity.
