### ISSUE TITLE
Property 'declare' is ignored for exchanges and queues

### ISSUE THREAD

**Issue by joorloohuis** [mikemadisonweb/yii2-rabbitmq#38]
Judging by the code in components/Routing.php, the 'declare' property in the configuration of a queue or an exchange is ignored, and the declaration is done regardless of the property being false. I would have expected it to result in the queue or exchange just being flagged as declared, without actually declaring them.

**Comment by mikemadisonweb** [comment]
Hello,
Good catch! I have removed `declare` property from documentation as despite it exist in the AMQP spec it doesn't used by [php-amqp](https://github.com/php-amqplib/php-amqplib/blob/master/PhpAmqpLib/Channel/AMQPChannel.php#L355) lib.
In the scope of the extension, the global `auto-declare` property should be used in order to control this functionality.

**Comment by joorloohuis** [comment]
I saw the auto-declare property, and I've already made some adjustments in my code for it. Having said that, it looks like the isExchangeExists() and isQueueExists() methods in routing will declare exchanges and queues regardless of the auto-declare property, but I haven't tested that yet.

**Comment by mikemadisonweb** [comment]
It will work. The logic you are taking about is in the Consumer and Publisher, e.g https://github.com/mikemadisonweb/yii2-rabbitmq/blob/24a7f764004fee098809b61c7b945a88cef49e1f/components/Consumer.php#L190

**Comment by joorloohuis** [comment]
Agreed. It wasn't obvious to me for the producer because it calls isExchangeExists from the Router, but a quick test shows that with auto_declare set to false no exchange is created when a message is published to an exchange that doesn't exist yet.
