### ISSUE TITLE
Issues create an SSL Connection

### ISSUE THREAD

**Issue by FreekGille** [mikemadisonweb/yii2-rabbitmq#51]
I'm trying to connect with a broker over an SSL Connection. The below snippet is a copy of the connection settings part in the `main.php` file.

```
'connections' => [
    [
        'type' => AMQPSSLConnection::class,
        'host' => $host,
        'port' => 5671,
        'user' => $username,
        'password' => $password,
        'vhost' => $vhost,
        'ssl_context' => [
            'verify_peer' => true,
        ],
    ]
],
```

In `AbstractConnectionFactory.php`, the `createConnection` method sets up the connection. The settings are passed to the class as follows:

```
return new $this->_class(
    $this->_parameters['host'],
    $this->_parameters['port'],
    $this->_parameters['user'],
    $this->_parameters['password'],
    $this->_parameters['vhost'],
    false,      // insist
    'AMQPLAIN', // login_method
    null,       // login_response
    'en_EN',    // locale
    $this->_parameters['connection_timeout'],
    $this->_parameters['read_write_timeout'],
    $this->_parameters['ssl_context'],
    $this->_parameters['keepalive'],
    $this->_parameters['heartbeat'],
    $this->_parameters['channel_rpc_timeout']
);
```

With working settings, the connection fails with the following error message:
>Exception 'PhpAmqpLib\Exception\AMQPConnectionClosedException' with message 'Broken pipe or closed connection'

When I change the passing of the variables to this order/variables, I can successfully connect to the broker:
```
return new $this->_class(
    $this->_parameters['host'],
    $this->_parameters['port'],
    $this->_parameters['user'],
    $this->_parameters['password'],
    $this->_parameters['vhost'],
    $this->_parameters['ssl_context'],
);
```

Even though it works, I rather don't want to change the code of this extension. Am I doing something wrong in setting up the connection through the standard `AbstractConnection` or something in my `main.php` settings that's wrong?

**Comment by mikemadisonweb** [comment]
Hi @FreekGille and thanks for your interest in the extension.
You are right, AMQPSSLConnection have different constructor definition than others and it was overlooked completely.
Considering this I can suggest two ways to go:
1) Add PR for the extension taken in consideration specifics of AMQPSSLConnection in AbstractConnectionFactory. If you dont have time for it, I will add it myself eventually.
2) A bit hacky but should work: pass AMQPStreamConnection as the connection type and add this function in order to process your ssl_context options: https://github.com/php-amqplib/php-amqplib/blob/a44b6df6b260fd13c362bfbb2bb2daa8c4b670f2/PhpAmqpLib/Connection/AMQPSSLConnection.php#L59

**Comment by FreekGille** [comment]
Hi @mikemadisonweb!

Thanks for your reply. I'm not sure I feel confident enough in my programming and knowledge on AMQP to correctly implement and add a PR to fix this. I've fixed it for now using the solution mentioned in my original post so no rush on implementing a fix for this (also seems no one else had an issue with this use case yet anyway).
Thanks for the amazing work on this extension and wishing you a great day!

**Comment by mikemadisonweb** [comment]
Fixed in https://github.com/mikemadisonweb/yii2-rabbitmq/pull/53.
